# Generated by Django 5.0.6 on 2024-05-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('account_type', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
