# Generated by Django 5.0.6 on 2024-06-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(help_text='Username has to be at minimum 8 characters.', max_length=255, primary_key=True, serialize=False),
        ),
    ]
