# Generated by Django 5.0.6 on 2024-06-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(help_text="A password can't be too similar to the users other personal information.<br>A password must contain at least 8 characters.<br> A password can't be a commonly used password.A password can't be entirely numeric.", max_length=255),
        ),
    ]
