# Generated by Django 5.0.6 on 2024-05-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Coadmin')], default=0),
        ),
    ]
