# Generated by Django 5.0.6 on 2024-06-14 21:48

import django.db.models.deletion
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('des', models.TextField()),
                ('salary', models.PositiveIntegerField(default=0)),
                ('admin', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_company', to='jobs.job')),
            ],
            options={
                'unique_together': {('name', 'job')},
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('admin', models.CharField(default=None, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('resume', models.FileField(upload_to=jobs.models.generate_unique_filename)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applicant', to='jobs.job')),
            ],
            options={
                'unique_together': {('username', 'job', 'time')},
            },
        ),
    ]
