# Generated by Django 5.0.6 on 2024-05-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('jobid', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('admin', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'unique_together': {('username', 'jobid', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jobid', models.CharField(max_length=5)),
            ],
            options={
                'unique_together': {('name', 'jobid')},
            },
        ),
    ]
