# Generated by Django 5.0.6 on 2024-05-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_company_id_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='jobid',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
