# Generated by Django 5.0.6 on 2024-05-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_applicant_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(default=None, upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
