# Generated by Django 5.0.6 on 2024-05-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_applicant_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
