# Generated by Django 5.0.6 on 2024-05-23 22:22

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_applicant_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(upload_to=jobs.models.generate_unique_filename),
        ),
    ]
